'use strict';

var App = App || {};

App.Templates.Week = _.template([    
    '<div class="week">',
        '<div class="table-wrapper_day">',
            '<table class="day">',
                '<tr class="table-header">',
                    '<th class="cell-header"></th>',
                    '<% var today = currentDay.day + \'.\' + currentDay.month; %>',
                    '<% var _format = function (n) { return n < 10 ? \'0\' + n : n } %>',
                    '<% var year = currentDay.year; %>',
                    '<% var currentWeekDay = false; %>',
                    '<th class="cell-header <% if (today === Mo.day && year === Mo.year) { currentWeekDay = \'1\' %>current<% } %>">Понедельник <sup class="cell-header_date" data-year="<%= Mo.year %>"><%= Mo.day %></sup></th>',
                    '<th class="cell-header <% if (today === Tu.day && year === Tu.year) { currentWeekDay = \'2\' %>current<% } %>">Вторник <sup class="cell-header_date" data-year="<%= Tu.year %>"><%= Tu.day %></sup></th>',
                    '<th class="cell-header <% if (today === We.day && year === We.year) { currentWeekDay = \'3\' %>current<% } %>">Среда <sup class="cell-header_date" data-year="<%= We.year %>"><%= We.day %></sup></th>',
                    '<th class="cell-header <% if (today === Th.day && year === Th.year) { currentWeekDay = \'4\' %>current<% } %>">Четверг <sup class="cell-header_date" data-year="<%= Th.year %>"><%= Th.day %></sup></th>',
                    '<th class="cell-header <% if (today === Fr.day && year === Fr.year) { currentWeekDay = \'5\' %>current<% } %>">Пятница <sup class="cell-header_date" data-year="<%= Fr.year %>"><%= Fr.day %></sup></th>',
                    '<th class="cell-header <% if (today === Sa.day && year === Sa.year) { currentWeekDay = \'6\' %>current<% } %>">Суббота <sup class="cell-header_date" data-year="<%= Sa.year %>"><%= Sa.day %></sup></th>',
                    '<th class="cell-header <% if (today === Su.day && year === Su.year) { currentWeekDay = \'7\' %>current<% } %>">Воскресенье <sup class="cell-header_date" data-year="<%= Su.year %>"><%= Su.day %></sup></th>',
                 '</tr>',
            '</table>',
        '</div>',
        '<div class="table-wrapper_time">',
            '<table class="time">',
                '<% var hours = 24; %>',
                '<% for (var i = 0; i < hours; i++) { %>',
                    '<tr>',
                        '<td class="time-cell"><%= i < 10 ? \'0\' + i : i %>:00</td>',
                    '</tr>',
                '<% } %>',
            '</table>',
        '</div>',
        '<div class="table-wrapper_event" id="calendar">',
            '<% var days = [\'Понедельник\', \'Вторник\', \'Среда\', \'Четверг\', \'Пятница\', \'Суббота\', \'Воскресенье\'] %>',
            '<% var dates = [Mo.fullDate, Tu.fullDate, We.fullDate, Th.fullDate, Fr.fullDate, Sa.fullDate, Su.fullDate] %>',
            '<% var j = 0, k = 0, h = 0, time = \'00\' %>',
            '<% for (var i = 0; i < (days.length * 2) * hours; i++) { %>',
                '<% if (j + 1 > days.length) { %>',
                    '<% j = 0; %>',
                '<% } %>',
                '<% if (i > 0 && i % (days.length * 2) === 0) { %>',
                    '<% k++; %>',
                '<% } %>',
                '<% if (i > 0 && h <= (days.length * 2) && (i % days.length) === 0) { %>',
                    '<% time = \'30\' ; %>',
                '<% } %>',
                '<% if (h === (days.length * 2)) { %>',
                    '<% h = 0 ; %>',
                    '<% time = \'00\' ; %>',
                '<% } %>',
                '<% if (i % days.length === 0) { %>',
					'<% var y = 0; %>',
                    '<div class="cell-row">',
                '<% } %>',
                        '<div class="cell <% if (y == (currentWeekDay - 1)) { %>',
							'current',
							'<% } %>"',
							'data-calendar=\'{',
                            '"weekDay": "<%= days[j] %>", ',
                            '"date": "<%= dates[j] %>", ',
                            '"startTime": "<%= _format(k) %>:<%= time %>", ',
                            '"endTime": "<%= time === \'00\' ? _format(k) : _format(k + 1) %>:<%= time === \'00\' ? \'30\' : \'00\' %>", ',
                            '"id": "<%= i %>"}\'>',
                        '<% h++; %>',
                        '<% j++; %>',
						'<% y++; %>',
                        '</div>',
                '<% if (j + 1 > days.length) { %>',
                    '</div>',
                '<% } %>',
            '<% } %>',
            '<div class="event-info_container"></div>',
        '</div>',
    '</div>'
].join(''));